name: purebdgen
channels:
    - defaults
    - anaconda
dependencies:
    - python=3.12
    - tqdm
    - numpy
    - pyparsing
    - pip
    - pydantic
    - pip:
        - torch==2.8.0
        - torchvision
        - tensorboardX